# Generated by Django 5.2 on 2025-04-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeamToBeamSplice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_length', models.FloatField()),
                ('flange_thickness', models.FloatField()),
                ('web_thickness', models.FloatField()),
                ('bolt_diameter', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
